In [6]:
import numpy as np

In [7]:
n = 30
m = 40

In [8]:
two_dim_matrix = np.random.randint(1,100,(m, n))

In [10]:
two_dim_matrix[1]

array([76, 65, 76, 35,  2, 48, 18, 35, 29, 48, 48, 42, 18, 64, 87, 67, 90,
       91, 19, 45, 32, 73, 71, 55, 54, 73, 35, 22, 91, 21])

In [11]:
third_column = two_dim_matrix [:,2]

In [12]:
third_column

array([35, 76, 57, 11, 87,  3, 22, 20, 47, 93,  1, 69, 75, 39, 25, 57,  1,
        5, 39, 89, 47, 54, 15, 37,  9, 77, 83, 20, 25, 87, 92, 40, 57, 58,
       15, 68, 59, 70, 89, 47])

In [14]:
two_dim_matrix[-1]=7

In [16]:
two_dim_matrix[-1]

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7])

In [17]:
two_dim_matrix[:,-1] = two_dim_matrix[:,0] + two_dim_matrix[:,1]

In [19]:
two_dim_matrix

array([[ 10,  59,  35, ...,  51,  77,  69],
       [ 76,  65,  76, ...,  22,  91, 141],
       [ 95,   3,  57, ...,  57,  96,  98],
       ...,
       [ 11,  43,  70, ...,   4,  74,  54],
       [ 11,  43,  89, ...,  45,  34,  54],
       [  7,   7,   7, ...,   7,   7,  14]])